### ISSUE TITLE
Deprecated warning during homebrew upgrade related to this tap

### ISSUE THREAD

**Issue by ghost** [mfuentesg/homebrew-tap#1]
Hello sir,

When I run `brew upgrade`, I receive the following warning notification:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the mfuentesg/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/mfuentesg/homebrew-tap/ksd.rb:6
```

I think [line 6](https://github.com/mfuentesg/homebrew-tap/blob/master/ksd.rb#L6) of the formula can be removed as it's not used anymore in future homebrew versions.

If preferred, I can make a PR later this week to remove the deprecated line... 

btw: Thanks a lot for creating `ksd` and providing a homebrew tap to install it on mac, it's one of my most frequently used tools in my toolchain :)

**Comment by mfuentesg** [comment]
Hey @summerflip sorry for the mega delay, thanks for your comment.
I have fixed the warnings upgrading the version of goreleaser. 

Just FYI, all the code it's autogenerated by goreleaser available on this repo https://github.com/mfuentesg/ksd.

Have a great day!

**Comment by mfuentesg** [comment]
Btw, now ksd has the version 1.0.7. In order to have last version just run `brew upgrade ksd`.

Bye!
